remote-theme: just-the-docs/just-the-docs
markdown: kramdown
has-toc: false

just-the-docs:
  logo: "/manual/assets/images/mib64-icon-main-100x100l.png"
  nav-enabled: true
  search-enabled: true
  heading-anchors: true
  collections:
    manual:
      output: true
      permalink: /:path/
